on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: votingaks.azurecr.io
        username: ${{ secrets.acr_votingaks_username }}
        password: ${{ secrets.acr_votingaks_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t votingaks.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push votingaks.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclusterb3c7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclusterb3c7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclusterb3c7
        container-registry-url: votingaks.azurecr.io
        container-registry-username: ${{ secrets.acr_votingaks_username }}
        container-registry-password: ${{ secrets.acr_votingaks_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclusterb3c7
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          votingaks.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
